/* ===== Static data: muscles, equipment, exercise library, programme templates ===== */
const MUSCLES = [
  { id: 'chest', name: 'Chest', big: true },
  { id: 'back', name: 'Back', big: true },
  { id: 'shoulders', name: 'Shoulders' },
  { id: 'biceps', name: 'Biceps' },
  { id: 'triceps', name: 'Triceps' },
  { id: 'quads', name: 'Quads', big: true },
  { id: 'hamstrings', name: 'Hamstrings', big: true },
  { id: 'glutes', name: 'Glutes' },
  { id: 'calves', name: 'Calves' },
  { id: 'core', name: 'Core' },
  { id: 'other', name: 'Other' },
];
const MUSCLE_NAME = Object.fromEntries(MUSCLES.map(m => [m.id, m.name]));
const TRACKED_MUSCLES = MUSCLES.filter(m => m.id !== 'other').map(m => m.id);

const EQUIPMENT = [
  { id: 'barbell', name: 'Barbell' },
  { id: 'dumbbell', name: 'Dumbbell' },
  { id: 'cable', name: 'Cable' },
  { id: 'machine', name: 'Machine' },
  { id: 'smith', name: 'Smith machine' },
  { id: 'bodyweight', name: 'Bodyweight' },
  { id: 'other', name: 'Other' },
];
const EQUIP_NAME = Object.fromEntries(EQUIPMENT.map(e => [e.id, e.name]));

const EQUIP_PRESETS = {
  commercial: ['barbell', 'dumbbell', 'cable', 'machine', 'smith', 'bodyweight', 'other'],
  home: ['barbell', 'dumbbell', 'bodyweight', 'other'],
};

/* Movement patterns drive replacement suggestions and default coaching text */
const PATTERNS = {
  hpush: { name: 'Horizontal press', tips: ['Keep shoulder blades pulled back and down against the bench.', 'Lower under control and touch the same point each rep.'], mistakes: ['Flaring elbows straight out to 90°.', 'Bouncing the weight or lifting the hips.'] },
  inpush: { name: 'Incline press', tips: ['A 30° incline hits the upper chest without turning it into a shoulder press.', 'Keep a slight arch and your feet planted.'], mistakes: ['Setting the bench too steep.', 'Cutting the range short at the bottom.'] },
  vpush: { name: 'Overhead press', tips: ['Brace your abs and squeeze your glutes so your lower back stays neutral.', 'Press in a straight line and finish with arms by your ears.'], mistakes: ['Leaning back excessively.', 'Stopping the bar in front of the face instead of overhead.'] },
  dip: { name: 'Dip', tips: ['Lean forward slightly for more chest, stay upright for more triceps.', 'Descend until upper arms are roughly parallel to the floor.'], mistakes: ['Dropping too deep with rounded shoulders.', 'Swinging the legs for momentum.'] },
  fly: { name: 'Chest fly', tips: ['Keep a soft, fixed bend in the elbows.', 'Think about bringing your upper arms together rather than your hands.'], mistakes: ['Turning the fly into a press by bending the elbows.', 'Using a weight so heavy the stretch is lost.'] },
  hpull: { name: 'Row', tips: ['Lead with the elbows and squeeze the shoulder blades together.', 'Let the shoulder blades travel forward at the stretch.'], mistakes: ['Using body swing to move the weight.', 'Shrugging the weight up toward the ears.'] },
  vpull: { name: 'Vertical pull', tips: ['Drive the elbows down toward your back pockets.', 'Control the way up and get a full stretch at the top.'], mistakes: ['Leaning far back and turning it into a row.', 'Half reps that never reach a full hang.'] },
  pullover: { name: 'Pullover', tips: ['Keep arms nearly straight and move from the shoulder.', 'Squeeze the lats hard at the bottom.'], mistakes: ['Bending the elbows and turning it into a pushdown.', 'Using momentum from the torso.'] },
  shrug: { name: 'Shrug', tips: ['Lift straight up toward the ears and pause at the top.', 'Keep your arms relaxed like hooks.'], mistakes: ['Rolling the shoulders in circles.', 'Very short, bouncing reps.'] },
  latraise: { name: 'Lateral raise', tips: ['Lead with the elbows and raise out to the side, slightly forward.', 'Stop around shoulder height and control the lowering.'], mistakes: ['Swinging the torso to throw the weight up.', 'Shrugging the traps as you lift.'] },
  reardelt: { name: 'Rear delt', tips: ['Move the arms out wide, away from the body.', 'Keep the shoulder blades fairly still to bias the rear delts.'], mistakes: ['Pulling with the upper back and traps.', 'Going too heavy and cutting the range.'] },
  curl: { name: 'Curl', tips: ['Keep the elbows still by your sides.', 'Lower slowly to a full stretch.'], mistakes: ['Swinging the hips to start the rep.', 'Letting the elbows drift forward at the top.'] },
  hammer: { name: 'Hammer curl', tips: ['Keep a neutral (palms-in) grip throughout.', 'Control the lowering phase.'], mistakes: ['Swinging the weights.', 'Cutting the bottom of the rep short.'] },
  tricepext: { name: 'Overhead extension', tips: ['Keep elbows pointing forward and fairly narrow.', 'Get a deep stretch behind the head.'], mistakes: ['Flaring the elbows wide.', 'Arching the lower back to move the weight.'] },
  pushdown: { name: 'Pushdown', tips: ['Pin your elbows to your sides.', 'Fully lock out and squeeze at the bottom.'], mistakes: ['Leaning over the handle and using body weight.', 'Letting the elbows travel forward and back.'] },
  squat: { name: 'Squat', tips: ['Brace hard before each rep and keep the bar over mid-foot.', 'Let the knees travel forward over the toes as you descend.'], mistakes: ['Knees caving inward.', 'Cutting depth as the weight gets heavier.'] },
  lunge: { name: 'Lunge / split squat', tips: ['Take a stable stance and drop the back knee straight down.', 'Drive through the front foot.'], mistakes: ['Pushing mostly off the back leg.', 'Wobbling because the stance is too narrow.'] },
  legpress: { name: 'Leg press', tips: ['Lower until your hips are just about to roll off the pad.', 'Push through the whole foot.'], mistakes: ['Locking the knees hard at the top.', 'Letting the lower back peel off the seat.'] },
  legext: { name: 'Leg extension', tips: ['Line the knee up with the machine pivot.', 'Pause briefly at the top.'], mistakes: ['Kicking the weight up with momentum.', 'Lifting the hips off the seat.'] },
  hinge: { name: 'Hip hinge', tips: ['Push the hips back and keep the bar close to your legs.', 'Keep a neutral spine from start to finish.'], mistakes: ['Rounding the lower back.', 'Squatting the weight up instead of hinging.'] },
  legcurl: { name: 'Leg curl', tips: ['Keep the hips pressed into the pad.', 'Control the stretch on the way back.'], mistakes: ['Lifting the hips to cheat the weight.', 'Partial reps without a full stretch.'] },
  hipthrust: { name: 'Hip thrust', tips: ['Tuck the chin and ribs, then drive through the heels.', 'Pause at full hip extension.'], mistakes: ['Over-arching the lower back at the top.', 'Feet too far forward, shifting work to the hamstrings.'] },
  abduct: { name: 'Hip abduction', tips: ['Lean slightly forward to bias the upper glutes.', 'Control the return.'], mistakes: ['Letting the pads slam back together.', 'Very short reps.'] },
  kickback: { name: 'Glute kickback', tips: ['Drive the leg back from the hip, not the lower back.', 'Squeeze the glute at the end.'], mistakes: ['Arching the lower back to go further.', 'Swinging the leg.'] },
  calf: { name: 'Calf raise', tips: ['Pause for a second in the deep stretch at the bottom.', 'Rise as high as possible onto the big toe.'], mistakes: ['Bouncing out of the bottom.', 'Bending the knees to help the weight.'] },
  trunkflex: { name: 'Crunch / leg raise', tips: ['Curl the spine; think ribs toward hips.', 'Exhale hard as you contract.'], mistakes: ['Pulling with the arms or hip flexors.', 'Rushing reps.'] },
  antiext: { name: 'Anti-extension', tips: ['Keep ribs down and glutes squeezed.', 'Stop before the lower back sags.'], mistakes: ['Letting the hips drop.', 'Holding your breath the whole time.'] },
  rotation: { name: 'Anti-rotation', tips: ['Resist the cable pulling you around.', 'Keep hips and shoulders square.'], mistakes: ['Standing too close to the stack.', 'Letting the torso twist.'] },
  carry: { name: 'Carry', tips: ['Stand tall, shoulders down, walk with short quick steps.', 'Crush the handles.'], mistakes: ['Leaning to one side.', 'Letting the shoulders round forward.'] },
  forearm: { name: 'Forearm', tips: ['Use a full range at the wrist.', 'Control the lowering.'], mistakes: ['Using the whole arm.', 'Going too heavy for a full range.'] },
};

/* type: heavy = main strength compound, compound = supporting compound, isolation */
function X(id, name, muscle, sec, eq, pat, type, focus, steps, tips, mistakes) {
  return { id, name, muscle, sec, eq, pat, type, focus: focus || '', steps: steps ? steps.split('|') : [], tips: tips ? tips.split('|') : null, mistakes: mistakes ? mistakes.split('|') : null };
}

const LIBRARY = [
  // CHEST
  X('bb_bench', 'Barbell Bench Press', 'chest', ['triceps', 'shoulders'], 'barbell', 'hpush', 'heavy', 'Mid chest',
    'Lie with eyes under the bar, feet flat and shoulder blades squeezed together.|Grip slightly wider than shoulders and unrack with straight arms.|Lower the bar to the lower chest with elbows about 45–70° from the body.|Press up and slightly back to lockout over the shoulders.',
    'Keep your upper back tight and create a small arch.|Touch the chest lightly on every rep for consistent range.|Use a spotter or safety pins when pushing close to failure.',
    'Bouncing the bar off the chest.|Wrists bent back instead of stacked over the forearm.|Hips lifting off the bench.'),
  X('incline_bb', 'Incline Barbell Press', 'chest', ['shoulders', 'triceps'], 'barbell', 'inpush', 'heavy', 'Upper chest',
    'Set the bench to about 30°.|Unrack with shoulder blades pinned back.|Lower the bar to the upper chest just below the collarbone.|Press straight up to lockout.'),
  X('db_bench', 'Dumbbell Bench Press', 'chest', ['triceps', 'shoulders'], 'dumbbell', 'hpush', 'compound', 'Mid chest',
    'Sit with dumbbells on your thighs, then lie back and kick them into position.|Start with arms extended over the chest.|Lower until you feel a deep chest stretch, elbows slightly tucked.|Press back up, bringing the dumbbells toward each other.'),
  X('incline_db', 'Incline Dumbbell Press', 'chest', ['shoulders', 'triceps'], 'dumbbell', 'inpush', 'compound', 'Upper chest',
    'Set the bench to 30°.|Press the dumbbells up over the upper chest.|Lower slowly to a deep stretch beside the chest.|Press up and slightly in.'),
  X('machine_chest', 'Machine Chest Press', 'chest', ['triceps', 'shoulders'], 'machine', 'hpush', 'compound', 'Mid chest',
    'Adjust the seat so the handles line up with mid-chest.|Keep your back against the pad and shoulder blades pulled back.|Press to almost full lockout.|Return slowly until you feel a stretch.'),
  X('smith_bench', 'Smith Machine Bench Press', 'chest', ['triceps', 'shoulders'], 'smith', 'hpush', 'compound', 'Mid chest',
    'Position the bench so the bar lands on your lower chest.|Unhook the bar with shoulder blades pulled back.|Lower under control to the chest.|Press up to lockout and re-hook at the end.'),
  X('smith_incline', 'Smith Machine Incline Press', 'chest', ['shoulders', 'triceps'], 'smith', 'inpush', 'compound', 'Upper chest',
    'Set a 30° bench under the Smith bar so it reaches your upper chest.|Unhook with a grip slightly wider than shoulders.|Lower to just below the collarbone.|Press to lockout.'),
  X('dips', 'Chest Dip', 'chest', ['triceps', 'shoulders'], 'bodyweight', 'dip', 'compound', 'Lower chest',
    'Support yourself on the bars with arms locked.|Lean the torso forward slightly.|Lower until your shoulders are just below the elbows.|Press back up to lockout. Add weight with a belt once 12+ reps is easy.'),
  X('cable_fly', 'Cable Fly', 'chest', ['shoulders'], 'cable', 'fly', 'isolation', 'Mid chest',
    'Set pulleys around shoulder height and take a staggered stance.|Start with arms wide and a soft bend in the elbows.|Bring the handles together in a hugging arc in front of the chest.|Return slowly to a full stretch.'),
  X('pec_deck', 'Pec Deck', 'chest', ['shoulders'], 'machine', 'fly', 'isolation', 'Mid chest',
    'Set the seat so the handles are at chest height.|Keep your back on the pad and chest up.|Bring the handles together and squeeze.|Return until you feel a strong stretch.'),
  X('db_fly', 'Dumbbell Fly', 'chest', ['shoulders'], 'dumbbell', 'fly', 'isolation', 'Mid chest',
    'Lie on a flat bench with dumbbells over the chest, palms facing.|With a slight elbow bend, lower the arms out wide.|Stop at a comfortable deep stretch.|Squeeze the chest to bring them back up.'),
  X('low_high_fly', 'Low-to-High Cable Fly', 'chest', ['shoulders'], 'cable', 'fly', 'isolation', 'Upper chest',
    'Set pulleys at the lowest position.|Start with arms low and slightly behind you.|Sweep the handles up and together to chin height.|Lower slowly back to the stretch.'),
  X('pushup', 'Push-Up', 'chest', ['triceps', 'shoulders', 'core'], 'bodyweight', 'hpush', 'compound', 'Mid chest',
    'Hands slightly wider than shoulders, body in a straight line.|Lower until the chest nearly touches the floor.|Keep elbows at roughly 45° from the body.|Push back up to lockout. Elevate the feet or add a plate to progress.'),

  // BACK
  X('deadlift', 'Deadlift', 'back', ['glutes', 'hamstrings', 'quads'], 'barbell', 'hinge', 'heavy', 'Posterior chain',
    'Stand with mid-foot under the bar, feet hip-width.|Hinge down and grip just outside the legs.|Bend knees until shins touch the bar, chest up, back flat.|Push the floor away and stand tall, keeping the bar against your legs.|Lower by pushing the hips back first.',
    'Pull the slack out of the bar before the floor breaks.|Keep the bar in contact with your legs the whole way.|Reset each rep rather than bouncing.',
    'Rounding the lower back.|Hips shooting up first so the lift becomes a stiff-leg pull.|Jerking the bar off the floor.'),
  X('pullup', 'Pull-Up', 'back', ['biceps'], 'bodyweight', 'vpull', 'compound', 'Lats',
    'Hang from the bar with an overhand grip slightly wider than shoulders.|Pull the shoulder blades down to start.|Drive the elbows down until the chin clears the bar.|Lower to a full hang. Add weight once 10+ reps is easy.'),
  X('chinup', 'Chin-Up', 'back', ['biceps'], 'bodyweight', 'vpull', 'compound', 'Lats',
    'Hang with an underhand grip at shoulder width.|Pull the chest toward the bar.|Get the chin over the bar.|Lower to a full hang.'),
  X('lat_pulldown', 'Lat Pulldown', 'back', ['biceps'], 'cable', 'vpull', 'compound', 'Lats',
    'Lock your thighs under the pad and grip slightly wider than shoulders.|Lean back slightly and pull the bar to the upper chest.|Squeeze the lats with elbows down by your sides.|Return to a full stretch overhead.'),
  X('cg_pulldown', 'Close-Grip Pulldown', 'back', ['biceps'], 'cable', 'vpull', 'compound', 'Lats',
    'Attach a close neutral-grip handle.|Pull toward the upper chest, elbows tucked.|Squeeze at the bottom.|Let the arms extend fully for a stretch.'),
  X('assisted_pullup', 'Assisted Pull-Up', 'back', ['biceps'], 'machine', 'vpull', 'compound', 'Lats',
    'Set the counterweight (more weight = more help).|Kneel or stand on the platform and grip the handles.|Pull until the chin is over the handles.|Lower under control. Progress by using less assistance.'),
  X('bb_row', 'Barbell Row', 'back', ['biceps', 'shoulders'], 'barbell', 'hpull', 'heavy', 'Upper back',
    'Hinge forward to about 45° with a flat back and soft knees.|Grip just outside shoulder width.|Row the bar to the lower ribs, leading with the elbows.|Lower to arms straight without losing your back position.'),
  X('db_row', 'One-Arm Dumbbell Row', 'back', ['biceps', 'shoulders'], 'dumbbell', 'hpull', 'compound', 'Lats',
    'Brace one hand and knee on a bench, back flat.|Let the dumbbell hang straight down.|Row it toward the hip, keeping the elbow close.|Lower to a full stretch.'),
  X('cable_row', 'Seated Cable Row', 'back', ['biceps', 'shoulders'], 'cable', 'hpull', 'compound', 'Mid back',
    'Sit tall with a slight knee bend and grab the handle.|Pull to the stomach, squeezing the shoulder blades.|Keep the torso mostly still.|Reach forward to a full stretch.'),
  X('chest_row', 'Chest-Supported Row', 'back', ['biceps', 'shoulders'], 'machine', 'hpull', 'compound', 'Upper back',
    'Set the chest pad so you can just reach the handles.|Keep your chest on the pad.|Row the elbows back and squeeze.|Return to a full stretch.'),
  X('tbar_row', 'T-Bar Row', 'back', ['biceps', 'shoulders'], 'other', 'hpull', 'compound', 'Mid back',
    'Straddle the bar and hinge forward with a flat back.|Grip the handle and brace.|Row toward the chest.|Lower to straight arms.'),
  X('smith_row', 'Smith Machine Row', 'back', ['biceps', 'shoulders'], 'smith', 'hpull', 'compound', 'Upper back',
    'Set the bar just below knee height.|Hinge forward with a flat back.|Row to the lower chest.|Lower with control.'),
  X('inverted_row', 'Inverted Row', 'back', ['biceps', 'shoulders'], 'bodyweight', 'hpull', 'compound', 'Upper back',
    'Set a bar at waist height and hang underneath with a straight body.|Pull your chest to the bar.|Squeeze the shoulder blades.|Lower to straight arms.'),
  X('straight_arm', 'Straight-Arm Pulldown', 'back', [], 'cable', 'pullover', 'isolation', 'Lats',
    'Stand facing a high pulley with a bar or rope.|Hinge slightly with arms almost straight.|Sweep the handle down to your thighs.|Return overhead to a stretch.'),
  X('bb_shrug', 'Barbell Shrug', 'back', ['other'], 'barbell', 'shrug', 'isolation', 'Traps',
    'Hold the bar at arm\'s length.|Shrug straight up toward the ears.|Pause for a second.|Lower fully.'),
  X('db_shrug', 'Dumbbell Shrug', 'back', ['other'], 'dumbbell', 'shrug', 'isolation', 'Traps',
    'Hold dumbbells at your sides.|Shrug straight up.|Pause at the top.|Lower to a full stretch.'),
  X('back_ext', 'Back Extension', 'back', ['glutes', 'hamstrings'], 'bodyweight', 'hinge', 'isolation', 'Lower back',
    'Set the pad just below the hip bones.|Cross arms or hold a plate at the chest.|Lower by hinging at the hips.|Rise until the body is straight — do not hyperextend.'),

  // SHOULDERS
  X('ohp', 'Overhead Press', 'shoulders', ['triceps', 'core'], 'barbell', 'vpush', 'heavy', 'Front delts',
    'Unrack the bar at collarbone height, grip just outside shoulders.|Brace abs and glutes.|Press straight up, moving your head back then through once the bar passes.|Lock out overhead with the bar over mid-foot.',
    'Squeeze glutes to stop your lower back arching.|Keep forearms vertical under the bar.',
    'Leaning back into a standing incline press.|Pressing the bar out in front of the face.'),
  X('db_shoulder', 'Seated Dumbbell Shoulder Press', 'shoulders', ['triceps'], 'dumbbell', 'vpush', 'compound', 'Front delts',
    'Sit on a bench set to about 80–90°.|Start with dumbbells at shoulder height.|Press up until arms are straight.|Lower back to shoulder height.'),
  X('machine_shoulder', 'Machine Shoulder Press', 'shoulders', ['triceps'], 'machine', 'vpush', 'compound', 'Front delts',
    'Adjust the seat so handles start at shoulder height.|Keep your back on the pad.|Press to near lockout.|Lower with control.'),
  X('smith_ohp', 'Smith Machine Shoulder Press', 'shoulders', ['triceps'], 'smith', 'vpush', 'compound', 'Front delts',
    'Place an upright bench under the bar.|Unhook at chin height.|Press to lockout.|Lower to chin level.'),
  X('landmine_press', 'Landmine Press', 'shoulders', ['chest', 'triceps'], 'other', 'vpush', 'compound', 'Front delts',
    'Hold the end of a landmine bar at shoulder height.|Brace and press up and forward.|Lock out the arm.|Lower under control.'),
  X('db_lateral', 'Dumbbell Lateral Raise', 'shoulders', [], 'dumbbell', 'latraise', 'isolation', 'Side delts',
    'Stand with dumbbells at your sides.|Raise them out to the sides with slightly bent elbows.|Stop around shoulder height.|Lower slowly.'),
  X('cable_lateral', 'Cable Lateral Raise', 'shoulders', [], 'cable', 'latraise', 'isolation', 'Side delts',
    'Set the pulley low and stand side-on.|Hold the handle with the far hand.|Raise the arm out to the side.|Lower slowly across the body.'),
  X('machine_lateral', 'Machine Lateral Raise', 'shoulders', [], 'machine', 'latraise', 'isolation', 'Side delts',
    'Adjust the seat so shoulders line up with the pivot.|Press the elbows into the pads.|Raise to shoulder height.|Lower with control.'),
  X('face_pull', 'Face Pull', 'shoulders', ['back'], 'cable', 'reardelt', 'isolation', 'Rear delts',
    'Set a rope at upper-chest to face height.|Pull toward your face, separating the rope ends.|Finish with elbows high and hands beside the ears.|Return slowly.'),
  X('rear_delt_fly', 'Reverse Pec Deck', 'shoulders', ['back'], 'machine', 'reardelt', 'isolation', 'Rear delts',
    'Face the pad with handles at shoulder height.|Sweep the arms out and back.|Pause briefly.|Return slowly.'),
  X('db_rear_delt', 'Bent-Over Rear Delt Raise', 'shoulders', ['back'], 'dumbbell', 'reardelt', 'isolation', 'Rear delts',
    'Hinge forward with dumbbells hanging below the chest.|Raise the arms out wide.|Squeeze at the top.|Lower slowly.'),

  // BICEPS
  X('bb_curl', 'Barbell Curl', 'biceps', ['other'], 'barbell', 'curl', 'isolation', '',
    'Hold the bar at shoulder width, palms up.|Curl up without moving the elbows.|Squeeze at the top.|Lower to full extension.'),
  X('ez_curl', 'EZ-Bar Curl', 'biceps', ['other'], 'barbell', 'curl', 'isolation', '',
    'Grip the angled part of the EZ bar.|Curl toward the shoulders.|Squeeze.|Lower slowly to full extension.'),
  X('db_curl', 'Dumbbell Curl', 'biceps', ['other'], 'dumbbell', 'curl', 'isolation', '',
    'Hold dumbbells at your sides, palms forward.|Curl up, keeping elbows still.|Squeeze at the top.|Lower fully.'),
  X('incline_curl', 'Incline Dumbbell Curl', 'biceps', [], 'dumbbell', 'curl', 'isolation', 'Long head',
    'Sit on a bench set to about 45° with arms hanging.|Curl without letting the elbows swing forward.|Squeeze at the top.|Lower to a deep stretch.'),
  X('hammer_curl', 'Hammer Curl', 'biceps', ['other'], 'dumbbell', 'hammer', 'isolation', 'Brachialis',
    'Hold dumbbells with palms facing in.|Curl up keeping the neutral grip.|Squeeze.|Lower fully.'),
  X('cable_curl', 'Cable Curl', 'biceps', [], 'cable', 'curl', 'isolation', '',
    'Attach a bar to a low pulley.|Curl up with elbows at your sides.|Squeeze.|Lower to full extension.'),
  X('preacher_curl', 'EZ-Bar Preacher Curl', 'biceps', [], 'barbell', 'curl', 'isolation', 'Short head',
    'Rest the backs of your arms on the preacher pad.|Curl the bar up.|Squeeze at the top.|Lower until arms are nearly straight.'),
  X('machine_curl', 'Machine Preacher Curl', 'biceps', [], 'machine', 'curl', 'isolation', 'Short head',
    'Adjust the seat so the elbows line up with the pivot.|Curl up and squeeze.|Lower under control.|Keep the upper arms on the pad throughout.'),
  X('bayesian_curl', 'Bayesian Cable Curl', 'biceps', [], 'cable', 'curl', 'isolation', 'Long head',
    'Face away from a low pulley, arm reaching behind you.|Curl forward keeping the elbow slightly behind the torso.|Squeeze.|Return to a deep stretch.'),

  // TRICEPS
  X('cgbp', 'Close-Grip Bench Press', 'triceps', ['chest', 'shoulders'], 'barbell', 'hpush', 'compound', '',
    'Grip the bar at about shoulder width.|Lower to the lower chest with elbows tucked.|Press to lockout.|Keep wrists stacked over elbows.'),
  X('pushdown', 'Cable Pushdown', 'triceps', [], 'cable', 'pushdown', 'isolation', 'Lateral head',
    'Attach a straight or V-bar to a high pulley.|Pin elbows to your sides.|Push down to full lockout.|Return until forearms are just above parallel.'),
  X('rope_pushdown', 'Rope Pushdown', 'triceps', [], 'cable', 'pushdown', 'isolation', 'Lateral head',
    'Attach a rope to a high pulley.|Push down and spread the rope at the bottom.|Squeeze.|Return with control.'),
  X('oh_cable_ext', 'Overhead Cable Extension', 'triceps', [], 'cable', 'tricepext', 'isolation', 'Long head',
    'Face away from a pulley with the rope overhead.|Keep elbows pointing forward.|Extend the arms fully.|Return to a deep stretch.'),
  X('skullcrusher', 'EZ-Bar Skull Crusher', 'triceps', [], 'barbell', 'tricepext', 'isolation', 'Long head',
    'Lie on a bench with the EZ bar over your chest.|Tilt the arms slightly back toward your head.|Bend the elbows to lower the bar behind the head.|Extend back up.'),
  X('db_oh_ext', 'Overhead Dumbbell Extension', 'triceps', [], 'dumbbell', 'tricepext', 'isolation', 'Long head',
    'Hold one dumbbell overhead with both hands.|Lower it behind the head.|Keep elbows pointing up.|Extend fully.'),
  X('machine_dip', 'Machine Dip', 'triceps', ['chest'], 'machine', 'dip', 'compound', '',
    'Sit with handles by your sides.|Press down until arms are straight.|Return until elbows are at about 90°.|Keep your torso upright.'),

  // QUADS
  X('back_squat', 'Back Squat', 'quads', ['glutes', 'core'], 'barbell', 'squat', 'heavy', '',
    'Set the bar on the upper back and unrack.|Stand with feet about shoulder width, toes slightly out.|Brace, then sit down between your heels until hips are at or below knees.|Drive up, keeping the chest up.',
    'Take a big breath and brace before each rep.|Push the knees out in line with the toes.|Film yourself from the side to check depth.',
    'Knees caving in.|Heels lifting.|Good-morning the weight up with the hips rising first.'),
  X('front_squat', 'Front Squat', 'quads', ['glutes', 'core'], 'barbell', 'squat', 'heavy', '',
    'Rest the bar on the front delts with elbows high.|Brace hard.|Squat down with an upright torso.|Drive up leading with the elbows.'),
  X('hack_squat', 'Hack Squat', 'quads', ['glutes'], 'machine', 'squat', 'compound', '',
    'Stand on the platform with shoulders under the pads.|Feet shoulder width, mid-platform.|Lower until thighs are below parallel.|Drive up without locking hard.'),
  X('pendulum_squat', 'Pendulum Squat', 'quads', ['glutes'], 'machine', 'squat', 'compound', '',
    'Set the shoulder pads and stand with feet mid-platform.|Descend as deep as you can control.|Drive up through the whole foot.|Keep the back flat on the pad.'),
  X('leg_press', 'Leg Press', 'quads', ['glutes'], 'machine', 'legpress', 'compound', '',
    'Sit with back flat and feet shoulder width on the platform.|Release the safeties.|Lower until knees are deeply bent.|Press back up without locking out hard.'),
  X('smith_squat', 'Smith Machine Squat', 'quads', ['glutes'], 'smith', 'squat', 'compound', '',
    'Set the bar on your upper back with feet slightly forward.|Unhook and brace.|Squat to depth.|Drive up.'),
  X('goblet_squat', 'Goblet Squat', 'quads', ['glutes', 'core'], 'dumbbell', 'squat', 'compound', '',
    'Hold a dumbbell vertically at your chest.|Squat down between your knees.|Keep the chest up.|Drive up.'),
  X('bss', 'Bulgarian Split Squat', 'quads', ['glutes'], 'dumbbell', 'lunge', 'compound', '',
    'Rest the back foot on a bench, front foot well forward.|Hold dumbbells at your sides.|Lower until the back knee nearly touches the floor.|Drive through the front foot. Do all reps on one leg, then switch.'),
  X('walking_lunge', 'Walking Lunge', 'quads', ['glutes'], 'dumbbell', 'lunge', 'compound', '',
    'Hold dumbbells at your sides.|Step forward into a lunge.|Drop the back knee toward the floor.|Push through and step into the next rep. Count reps per leg.'),
  X('leg_ext', 'Leg Extension', 'quads', [], 'machine', 'legext', 'isolation', '',
    'Adjust the seat so knees line up with the pivot.|Straighten the legs fully.|Pause at the top.|Lower slowly.'),

  // HAMSTRINGS
  X('rdl', 'Romanian Deadlift', 'hamstrings', ['glutes', 'back'], 'barbell', 'hinge', 'compound', '',
    'Hold the bar at hip height with a shoulder-width grip.|Soften the knees and push the hips back.|Slide the bar down the thighs until you feel a strong hamstring stretch.|Drive the hips forward to stand.',
    'Keep the bar touching your legs.|Stop where your back would start to round.',
    'Squatting down instead of hinging.|Rounding the lower back to reach the floor.'),
  X('db_rdl', 'Dumbbell Romanian Deadlift', 'hamstrings', ['glutes', 'back'], 'dumbbell', 'hinge', 'compound', '',
    'Hold dumbbells in front of your thighs.|Push the hips back with soft knees.|Lower to a hamstring stretch.|Stand tall.'),
  X('seated_curl', 'Seated Leg Curl', 'hamstrings', [], 'machine', 'legcurl', 'isolation', '',
    'Line up knees with the pivot and lock the thigh pad down.|Curl the legs back.|Squeeze.|Return slowly to full stretch.'),
  X('lying_curl', 'Lying Leg Curl', 'hamstrings', [], 'machine', 'legcurl', 'isolation', '',
    'Lie face down with the pad above the heels.|Curl toward the glutes.|Keep hips down.|Lower slowly.'),
  X('nordic', 'Nordic Curl', 'hamstrings', [], 'bodyweight', 'legcurl', 'isolation', '',
    'Kneel with ankles anchored.|Lower your body forward as slowly as possible.|Catch yourself with your hands.|Push back up and pull with the hamstrings.'),
  X('good_morning', 'Good Morning', 'hamstrings', ['back', 'glutes'], 'barbell', 'hinge', 'compound', '',
    'Place the bar on the upper back.|Soften the knees.|Hinge forward until the torso is near parallel.|Drive the hips forward to stand.'),

  // GLUTES
  X('hip_thrust', 'Barbell Hip Thrust', 'glutes', ['hamstrings'], 'barbell', 'hipthrust', 'compound', '',
    'Sit with upper back against a bench and the padded bar over your hips.|Plant feet hip-width.|Drive the hips up until the body is straight from knees to shoulders.|Lower under control.'),
  X('machine_hip_thrust', 'Machine Hip Thrust', 'glutes', ['hamstrings'], 'machine', 'hipthrust', 'compound', '',
    'Set the pad across your hips.|Plant feet and brace.|Drive the hips up and squeeze.|Lower slowly.'),
  X('sumo_dl', 'Sumo Deadlift', 'glutes', ['quads', 'hamstrings', 'back'], 'barbell', 'hinge', 'heavy', '',
    'Take a wide stance with toes turned out.|Grip inside the knees.|Push the knees out and chest up.|Push the floor away and lock out the hips.'),
  X('cable_kickback', 'Cable Glute Kickback', 'glutes', [], 'cable', 'kickback', 'isolation', '',
    'Attach an ankle strap to a low pulley.|Brace on the frame and hinge slightly.|Kick the leg back and up.|Return slowly.'),
  X('hip_abduction', 'Hip Abduction Machine', 'glutes', [], 'machine', 'abduct', 'isolation', 'Upper glutes',
    'Sit with pads on the outside of the knees.|Push the knees apart.|Pause.|Return slowly.'),

  // CALVES
  X('standing_calf', 'Standing Calf Raise', 'calves', [], 'machine', 'calf', 'isolation', '',
    'Stand with the balls of your feet on the platform.|Lower the heels into a deep stretch.|Pause.|Rise as high as possible.'),
  X('seated_calf', 'Seated Calf Raise', 'calves', [], 'machine', 'calf', 'isolation', 'Soleus',
    'Sit with the pad on your lower thighs.|Lower heels to a deep stretch.|Pause.|Rise fully.'),
  X('leg_press_calf', 'Leg Press Calf Raise', 'calves', [], 'machine', 'calf', 'isolation', '',
    'Place the balls of your feet on the bottom edge of the platform.|Keep the knees straight but not locked.|Lower into a stretch.|Press up fully.'),
  X('smith_calf', 'Smith Machine Calf Raise', 'calves', [], 'smith', 'calf', 'isolation', '',
    'Stand on a step under the Smith bar.|Unhook.|Lower heels into a stretch.|Rise fully.'),
  X('db_calf', 'Single-Leg Dumbbell Calf Raise', 'calves', [], 'dumbbell', 'calf', 'isolation', '',
    'Stand on a step on one foot holding a dumbbell.|Lower into a deep stretch.|Pause.|Rise fully. Count reps per leg.'),

  // CORE
  X('cable_crunch', 'Cable Crunch', 'core', [], 'cable', 'trunkflex', 'isolation', 'Abs',
    'Kneel facing a high pulley holding a rope beside your head.|Crunch down, bringing ribs toward hips.|Squeeze.|Return slowly.'),
  X('hanging_leg_raise', 'Hanging Leg Raise', 'core', [], 'bodyweight', 'trunkflex', 'isolation', 'Lower abs',
    'Hang from a bar.|Raise the legs by curling the pelvis up.|Pause.|Lower slowly without swinging.'),
  X('machine_crunch', 'Machine Crunch', 'core', [], 'machine', 'trunkflex', 'isolation', 'Abs',
    'Adjust the seat and grip the handles.|Crunch forward.|Squeeze.|Return slowly.'),
  X('plank', 'Plank', 'core', [], 'bodyweight', 'antiext', 'isolation', 'Abs',
    'Forearms on the floor, body straight.|Squeeze glutes and brace.|Hold.|Log seconds in the reps box.'),
  X('ab_wheel', 'Ab Wheel Rollout', 'core', [], 'other', 'antiext', 'isolation', 'Abs',
    'Kneel holding the wheel.|Roll forward keeping the ribs down.|Go as far as you can control.|Pull back with the abs.'),
  X('pallof', 'Pallof Press', 'core', [], 'cable', 'rotation', 'isolation', 'Obliques',
    'Stand side-on to a chest-height pulley.|Hold the handle at your chest.|Press straight out and resist rotation.|Return. Count reps per side.'),

  // OTHER
  X('farmers_carry', "Farmer's Carry", 'other', ['core', 'back'], 'dumbbell', 'carry', 'compound', 'Grip',
    'Pick up heavy dumbbells.|Stand tall.|Walk with short steps.|Log steps or seconds in the reps box.'),
  X('wrist_curl', 'Wrist Curl', 'other', [], 'dumbbell', 'forearm', 'isolation', 'Forearms',
    'Rest forearms on your thighs, palms up.|Let the dumbbells roll down.|Curl the wrists up.|Lower.'),
  X('reverse_curl', 'Reverse Curl', 'other', ['biceps'], 'barbell', 'forearm', 'isolation', 'Forearms',
    'Hold an EZ bar with an overhand grip.|Curl up.|Squeeze.|Lower slowly.'),
];

/* Slot lists for programme templates: first available option wins, liked exercises override */
const SLOTS = {
  benchH: ['bb_bench', 'db_bench', 'smith_bench', 'machine_chest', 'pushup'],
  inclineH: ['incline_bb', 'incline_db', 'smith_incline', 'machine_chest'],
  incline: ['incline_db', 'smith_incline', 'incline_bb', 'machine_chest', 'pushup'],
  press2: ['machine_chest', 'db_bench', 'smith_bench', 'dips', 'pushup'],
  fly: ['cable_fly', 'pec_deck', 'db_fly', 'low_high_fly'],
  ohpH: ['ohp', 'db_shoulder', 'machine_shoulder', 'smith_ohp', 'landmine_press'],
  ohp: ['db_shoulder', 'machine_shoulder', 'smith_ohp', 'ohp', 'landmine_press'],
  lateral: ['cable_lateral', 'db_lateral', 'machine_lateral'],
  lateral2: ['db_lateral', 'machine_lateral', 'cable_lateral'],
  rear: ['face_pull', 'rear_delt_fly', 'db_rear_delt'],
  rear2: ['rear_delt_fly', 'db_rear_delt', 'face_pull'],
  vpull: ['pullup', 'lat_pulldown', 'assisted_pullup', 'chinup'],
  vpull2: ['lat_pulldown', 'cg_pulldown', 'chinup', 'assisted_pullup', 'pullup'],
  rowH: ['bb_row', 'chest_row', 'tbar_row', 'db_row', 'smith_row', 'inverted_row'],
  row: ['cable_row', 'chest_row', 'db_row', 'tbar_row', 'inverted_row'],
  row2: ['db_row', 'chest_row', 'cable_row', 'inverted_row'],
  pullover: ['straight_arm', 'db_row'],
  curl: ['ez_curl', 'db_curl', 'cable_curl', 'bb_curl'],
  curl2: ['incline_curl', 'bayesian_curl', 'preacher_curl', 'machine_curl', 'db_curl'],
  hammer: ['hammer_curl', 'db_curl'],
  triOH: ['oh_cable_ext', 'db_oh_ext', 'skullcrusher'],
  triPD: ['rope_pushdown', 'pushdown', 'db_oh_ext'],
  triH: ['cgbp', 'machine_dip', 'dips', 'skullcrusher'],
  squatH: ['back_squat', 'hack_squat', 'smith_squat', 'leg_press', 'goblet_squat'],
  squat2: ['hack_squat', 'leg_press', 'pendulum_squat', 'front_squat', 'smith_squat', 'goblet_squat'],
  legpress: ['leg_press', 'hack_squat', 'smith_squat', 'goblet_squat'],
  lunge: ['bss', 'walking_lunge', 'goblet_squat'],
  legext: ['leg_ext', 'goblet_squat'],
  hingeH: ['deadlift', 'rdl', 'sumo_dl', 'db_rdl'],
  rdl: ['rdl', 'db_rdl', 'good_morning', 'back_ext'],
  legcurl: ['seated_curl', 'lying_curl', 'nordic', 'db_rdl'],
  legcurl2: ['lying_curl', 'seated_curl', 'nordic'],
  glute: ['hip_thrust', 'machine_hip_thrust', 'back_ext'],
  calf: ['standing_calf', 'smith_calf', 'leg_press_calf', 'db_calf'],
  calf2: ['seated_calf', 'leg_press_calf', 'standing_calf', 'db_calf'],
  abs: ['cable_crunch', 'hanging_leg_raise', 'machine_crunch', 'ab_wheel', 'plank'],
  abs2: ['hanging_leg_raise', 'ab_wheel', 'cable_crunch', 'plank'],
};

/* Each day: [name, slots...]; a slot may carry :main to mark the day's lead strength lift */
const TEMPLATES = [
  { id: 'fb2', name: 'Full Body ×2', days: 2, desc: 'Two full-body sessions. Each muscle trained twice a week — ideal when time is short.',
    plan: [['Full Body A', 'squatH:main', 'benchH', 'rowH', 'ohp', 'legcurl', 'curl', 'triPD'], ['Full Body B', 'hingeH:main', 'inclineH', 'vpull', 'legpress', 'lateral', 'triOH', 'calf']] },
  { id: 'fb3', name: 'Full Body ×3', days: 3, desc: 'Three full-body sessions. High frequency for every muscle with a strength focus on the big lifts.',
    plan: [['Full Body A', 'squatH:main', 'benchH', 'row', 'lateral', 'legcurl', 'curl'], ['Full Body B', 'hingeH:main', 'ohpH', 'vpull', 'legpress', 'triPD', 'calf'], ['Full Body C', 'benchH:main', 'squat2', 'row2', 'incline', 'rear', 'curl2', 'abs']] },
  { id: 'ppl3', name: 'Push / Pull / Legs', days: 3, desc: 'Classic three-day split. Each muscle once per week with plenty of volume per session.',
    plan: [['Push', 'benchH:main', 'ohp', 'incline', 'lateral', 'fly', 'triPD', 'triOH'], ['Pull', 'rowH:main', 'vpull', 'row', 'rear', 'curl', 'hammer'], ['Legs', 'squatH:main', 'rdl', 'legpress', 'legcurl', 'legext', 'calf']] },
  { id: 'cbl3', name: 'Chest & Back / Legs / Shoulders & Arms', days: 3, desc: 'Antagonist upper day, a leg day and an arms and delts day.',
    plan: [['Chest & Back', 'benchH:main', 'rowH', 'incline', 'vpull', 'fly', 'pullover'], ['Legs', 'squatH:main', 'rdl', 'legpress', 'legcurl', 'calf', 'abs'], ['Shoulders & Arms', 'ohpH:main', 'lateral', 'rear', 'curl', 'triPD', 'curl2', 'triOH']] },
  { id: 'ul4', name: 'Upper / Lower', days: 4, desc: 'The best all-round split for muscle and strength: each muscle twice a week, one heavier and one volume-focused day.',
    plan: [['Upper A', 'benchH:main', 'rowH', 'ohp', 'vpull2', 'lateral', 'triPD', 'curl'], ['Lower A', 'squatH:main', 'rdl', 'legpress', 'legcurl', 'calf', 'abs'], ['Upper B', 'ohpH:main', 'vpull', 'incline', 'row', 'fly', 'curl2', 'triOH'], ['Lower B', 'hingeH:main', 'squat2', 'lunge', 'legcurl2', 'calf2', 'abs2']] },
  { id: 'ulppl5', name: 'Upper / Lower + PPL', days: 5, desc: 'Upper and lower strength days followed by push, pull and legs volume days.',
    plan: [['Upper', 'benchH:main', 'rowH', 'ohp', 'vpull', 'curl', 'triPD'], ['Lower', 'squatH:main', 'rdl', 'legpress', 'legcurl', 'calf'], ['Push', 'inclineH:main', 'press2', 'lateral', 'fly', 'triOH'], ['Pull', 'vpull2:main', 'row', 'rear', 'curl2', 'hammer'], ['Legs', 'hingeH:main', 'squat2', 'lunge', 'legext', 'calf2', 'abs']] },
  { id: 'ppl6', name: 'Push / Pull / Legs ×2', days: 6, desc: 'High-volume six-day split. Every muscle twice a week — best for experienced lifters who recover well.',
    plan: [['Push A', 'benchH:main', 'ohp', 'incline', 'lateral', 'triPD', 'triOH'], ['Pull A', 'rowH:main', 'vpull', 'row2', 'rear', 'curl', 'hammer'], ['Legs A', 'squatH:main', 'rdl', 'legpress', 'legcurl', 'calf'], ['Push B', 'ohpH:main', 'inclineH', 'press2', 'lateral2', 'fly', 'triOH'], ['Pull B', 'vpull:main', 'row', 'pullover', 'rear2', 'curl2', 'hammer'], ['Legs B', 'hingeH:main', 'squat2', 'lunge', 'legcurl2', 'calf2', 'abs']] },
  { id: 'bro5', name: 'Body-Part Split', days: 5, desc: 'One muscle group per day. Lower frequency; works if you enjoy long, focused sessions.',
    plan: [['Chest', 'benchH:main', 'incline', 'press2', 'fly', 'dips'], ['Back', 'rowH:main', 'vpull', 'row', 'pullover', 'rear'], ['Legs', 'squatH:main', 'rdl', 'legpress', 'legcurl', 'legext', 'calf'], ['Shoulders', 'ohpH:main', 'lateral', 'rear2', 'lateral2', 'abs'], ['Arms', 'triH:main', 'curl', 'triPD', 'curl2', 'triOH', 'hammer']] },
];

const RECOMMENDED_TEMPLATE = { 2: 'fb2', 3: 'fb3', 4: 'ul4', 5: 'ulppl5', 6: 'ppl6' };
const DEFAULT_WEEKDAYS = { 1: [1], 2: [1, 4], 3: [1, 3, 5], 4: [1, 2, 4, 5], 5: [1, 2, 3, 5, 6], 6: [1, 2, 3, 4, 5, 6] };

const GEN_PRESETS = [
  { id: 'push', name: 'Push', muscles: ['chest', 'shoulders', 'triceps'] },
  { id: 'pull', name: 'Pull', muscles: ['back', 'biceps'] },
  { id: 'legs', name: 'Legs', muscles: ['quads', 'hamstrings', 'glutes', 'calves'] },
  { id: 'upper', name: 'Upper Body', muscles: ['chest', 'back', 'shoulders', 'biceps', 'triceps'] },
  { id: 'lower', name: 'Lower Body', muscles: ['quads', 'hamstrings', 'glutes', 'calves', 'core'] },
  { id: 'full', name: 'Full Body', muscles: ['quads', 'chest', 'back', 'hamstrings', 'shoulders', 'biceps', 'triceps'] },
  { id: 'ct', name: 'Chest + Triceps', muscles: ['chest', 'triceps'] },
  { id: 'bb', name: 'Back + Biceps', muscles: ['back', 'biceps'] },
  { id: 'sa', name: 'Shoulders + Arms', muscles: ['shoulders', 'biceps', 'triceps'] },
  { id: 'cb', name: 'Chest + Back', muscles: ['chest', 'back'] },
];

/* Rough intermediate starting weights (kg) used only for demo data */
const DEMO_BASE = { bb_bench: 80, incline_bb: 65, db_bench: 30, incline_db: 26, machine_chest: 70, smith_bench: 70, cable_fly: 15, pec_deck: 55, ohp: 50, db_shoulder: 22, machine_shoulder: 55, db_lateral: 10, cable_lateral: 7.5, face_pull: 22.5, rear_delt_fly: 40, pullup: 0, lat_pulldown: 65, cg_pulldown: 60, bb_row: 70, cable_row: 60, chest_row: 60, db_row: 32, straight_arm: 25, ez_curl: 32.5, db_curl: 14, incline_curl: 12, hammer_curl: 16, cable_curl: 25, bayesian_curl: 12.5, rope_pushdown: 27.5, pushdown: 32.5, oh_cable_ext: 25, db_oh_ext: 26, back_squat: 100, hack_squat: 100, leg_press: 180, bss: 20, leg_ext: 60, deadlift: 140, rdl: 100, seated_curl: 50, lying_curl: 45, standing_calf: 80, seated_calf: 50, cable_crunch: 45, hanging_leg_raise: 0, hip_thrust: 110, walking_lunge: 18, front_squat: 80, pendulum_squat: 80 };
